### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by spyhunter99** [michaelsteenkamp/rip#3]
Does this library just implement the algorithms of RIP or can it actually read RIP packets sent from a router? I'm looking at the code and it looks like it's just using plain old java serialization for the packet interpretation. I'm pretty sure RIP was made before Java so I'm in question whether or not that part works

**Comment by michaelsteenkamp** [comment]
This is simply an implementation of rip for demonstration purposes. It was
done as a theoretical assignment for university.

**Comment by itstheceo** [comment]
It was required that one computer ran several instances of the routing daemon in tandem, thus serialisation was necessary when reading and writing to and from sockets. How you decided to encode and decode the packet containing the routing table before you send it is an implementation detail, and not something specific to the RIP protocol itself.

**Comment by spyhunter99** [comment]
Ahh got it. Thanks for the info
